services:

### Postgres ##############################################
  postgres:
    image: postgres:16-alpine3.21
    container_name: "${COMPOSE_PROJECT_NAME}-postgres"
    restart: unless-stopped
    volumes:
      - ${DATA_PATH_HOST:-~/.sso/data}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sso}
      POSTGRES_USER: ${POSTGRES_USER:-developer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    networks:
      - backend

### Node #############################################
  node:
    image: node:24-alpine3.21
    container_name: "${COMPOSE_PROJECT_NAME}-node"
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./web:/usr/src/app
    ports:
      - "${WORKSPACE_BROWSERSYNC_HOST_PORT:-3000}:3000"
      - "${WORKSPACE_BROWSERSYNC_UI_HOST_PORT:-3001}:3001"
      - "${WORKSPACE_VUE_CLI_SERVE_HOST_PORT:-8082}:8082"
      - "${WORKSPACE_VUE_CLI_UI_HOST_PORT:-8000}:8000"
      - "${WORKSPACE_ANGULAR_CLI_SERVE_HOST_PORT:-4200}:4200"
      - "${WORKSPACE_VITE_PORT:-5173}:5173"
    tty: true
    networks:
      - backend

### Jaeger ################################################
  jaeger:
    image: jaegertracing/all-in-one:1.69.0
    container_name: "${COMPOSE_PROJECT_NAME}-jaeger"
    restart: unless-stopped
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - backend

networks:
  backend:
    driver: bridge
