// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT License",
            "url": "https://mit-license.org/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/oauth/signin": {
            "get": {
                "description": "Форма авторизации для клиентского приложения или для доступа в профиль пользователя",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Авторизация"
                ],
                "summary": "Форма авторизации и востановления доступа",
                "operationId": "AuthForm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID клиента",
                        "name": "client_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Ссылка клиента для обратного вызова",
                        "name": "redirect_uri",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML страница с формой авторизации"
                    },
                    "302": {
                        "description": "Передача кода по ссылке обратного вызова"
                    },
                    "400": {
                        "description": "Ошибка запроса"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            },
            "post": {
                "description": "Авторизация пользователя в клиентском приложении или для доступа в профиль пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Авторизация"
                ],
                "summary": "Авторизация пользователя",
                "operationId": "SignIn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID клиента",
                        "name": "client_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Ссылка клиента для обратного вызова",
                        "name": "redirect_uri",
                        "in": "query"
                    },
                    {
                        "description": "Данные для авторизации пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SignIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ссылка обратного вызова с кодом",
                        "schema": {
                            "$ref": "#/definitions/response.Location"
                        }
                    },
                    "302": {
                        "description": "Передача кода по ссылке обратного вызова"
                    },
                    "400": {
                        "description": "Ошибка запроса",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "401": {
                        "description": "Аунтефикация не пройдена",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "403": {
                        "description": "Нет доступа к клиенту",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "422": {
                        "description": "Ошибка ввода данных",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorValidate"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/oauth/token": {
            "post": {
                "description": "Получение токена доступа по коду или обновление токена доступа",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Авторизация"
                ],
                "summary": "Получение токена доступа",
                "operationId": "GenerateToken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID клиента",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Секрет клиента",
                        "name": "client_secret",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Единоразовый авторизационный код, если grant_type=authorization_code",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Единоразовый refresh токен, если grant_type=refresh_token",
                        "name": "refresh_token",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "authorization_code",
                            "refresh_token"
                        ],
                        "type": "string",
                        "description": "Тип разрешения",
                        "name": "grant_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Токен доступа",
                        "schema": {
                            "$ref": "#/definitions/response.AccessToken"
                        }
                    },
                    "401": {
                        "description": "Аунтефикация не пройдена",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "403": {
                        "description": "Нет доступа к клиенту",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.SignIn": {
            "description": "Авторизации пользователя по логину и паролю",
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "description": "Логин или email пользователя",
                    "type": "string",
                    "minLength": 3
                },
                "password": {
                    "description": "Пароль пользователя",
                    "type": "string",
                    "maxLength": 24,
                    "minLength": 6
                },
                "remember": {
                    "description": "Запомнить меня",
                    "type": "boolean"
                }
            }
        },
        "response.AccessToken": {
            "description": "Токен доступа",
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "Токен доступа",
                    "type": "string"
                },
                "expires_in": {
                    "description": "Время действия токена",
                    "type": "integer"
                },
                "info": {
                    "description": "Информация о пользователе",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.UserInfo"
                        }
                    ]
                },
                "refresh_token": {
                    "description": "Токен обновления",
                    "type": "string"
                },
                "token_type": {
                    "description": "Тип авторизации",
                    "type": "string"
                }
            }
        },
        "response.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "response.ErrorValidate": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "validate": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "response.Location": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                }
            }
        },
        "response.UserInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "Email пользователя",
                    "type": "string"
                },
                "name": {
                    "description": "Полное имя пользовтаеля",
                    "type": "string"
                },
                "uid": {
                    "description": "ID пользовтаеля",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.0",
	Host:             "127.0.0.1:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Single Sign-On Server",
	Description:      "Открытый протокол, обеспечивающий безопасную авторизацию простым и стандартным способом.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
