info:
  contact:
    name: Alnovi
    url: https://github.com/alnovi
  description: Single sign-on (сервис единого входа)
  license:
    name: MIT
    url: https://github.com/alnovi/sso/LICENSE.md
  title: SSO
  version: 1.0.0
paths: {}
swagger: "2.0"
