basePath: /
definitions:
  request.SignIn:
    description: Авторизации пользователя по логину и паролю
    properties:
      login:
        description: Логин или email пользователя
        minLength: 3
        type: string
      password:
        description: Пароль пользователя
        maxLength: 24
        minLength: 5
        type: string
      remember:
        description: Запомнить меня
        type: boolean
    required:
    - login
    - password
    type: object
  response.AccessToken:
    description: Токен доступа
    properties:
      access_token:
        description: Токен доступа
        type: string
      expires_in:
        description: Время действия токена
        type: integer
      info:
        allOf:
        - $ref: '#/definitions/response.UserInfo'
        description: Информация о пользователе
      refresh_token:
        description: Токен обновления
        type: string
      token_type:
        description: Тип авторизации
        type: string
    type: object
  response.Error:
    properties:
      message:
        type: string
      validate:
        additionalProperties:
          type: string
        type: object
    type: object
  response.Location:
    properties:
      location:
        type: string
    type: object
  response.UserInfo:
    properties:
      email:
        description: Email пользователя
        type: string
      name:
        description: Полное имя пользовтаеля
        type: string
      uid:
        description: ID пользовтаеля
        type: string
    type: object
host: 127.0.0.1:8081
info:
  contact: {}
  description: Открытый протокол, обеспечивающий безопасную авторизацию простым и
    стандартным способом.
  license:
    name: MIT License
    url: https://mit-license.org/
  title: Single Sign-On Server
  version: 0.0.0
paths:
  /oauth/signin:
    get:
      description: Форма авторизации для клиентского приложения или для доступа в
        профиль пользователя
      operationId: AuthForm
      parameters:
      - description: ID клиента
        in: query
        name: client_id
        type: string
      - description: Ссылка клиента для обратного вызова
        in: query
        name: redirect_uri
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: HTML страница с формой авторизации
        "302":
          description: Передача кода по ссылке обратного вызова
        "400":
          description: Ошибка запроса
        "500":
          description: Внутренняя ошибка сервера
      summary: Форма авторизации и востановления доступа
      tags:
      - Авторизация
    post:
      description: Авторизация пользователя в клиентском приложении или для доступа
        в профиль пользователя
      operationId: SignIn
      parameters:
      - description: ID клиента
        in: query
        name: client_id
        type: string
      - description: Ссылка клиента для обратного вызова
        in: query
        name: redirect_uri
        type: string
      - description: Данные для авторизации пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.SignIn'
      produces:
      - application/json
      responses:
        "200":
          description: Ссылка обратного вызова с кодом
          schema:
            $ref: '#/definitions/response.Location'
        "302":
          description: Передача кода по ссылке обратного вызова
        default:
          description: Ошибка запроса
          schema:
            $ref: '#/definitions/response.Error'
      summary: Авторизация пользователя
      tags:
      - Авторизация
  /oauth/token:
    post:
      description: Получение токена доступа по коду или обновление токена доступа
      operationId: GenerateToken
      parameters:
      - description: ID клиента
        in: query
        name: client_id
        required: true
        type: string
      - description: Секрет клиента
        in: query
        name: client_secret
        required: true
        type: string
      - description: Единоразовый авторизационный код, если grant_type=authorization_code
        in: query
        name: code
        type: string
      - description: Единоразовый refresh токен, если grant_type=refresh_token
        in: query
        name: refresh_token
        type: string
      - description: Тип разрешения
        enum:
        - authorization_code
        - refresh_token
        in: query
        name: grant_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Токен доступа
          schema:
            $ref: '#/definitions/response.AccessToken'
        "401":
          description: Аунтефикация не пройдена
          schema:
            $ref: '#/definitions/response.Error'
        "403":
          description: Нет доступа к клиенту
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/response.Error'
      summary: Получение токена доступа
      tags:
      - Авторизация
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
