name: master

on:
  push:
    branches:
      - master

jobs:
  govuln:
    name: govuln
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: govulncheck
        uses: golang/govulncheck-action@v1

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          skip-cache: true
          skip-pkg-cache: true


  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
#      - name: go get
#        run: go get ./...
      - name: go test
        run: go test ./... -count=1 -coverpkg=./... -coverprofile=./cover.out
      - name: check coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml

