name: master

on:
  push:
    branches:
      - master

jobs:
  govuln:
    name: govuln
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: govulncheck
        uses: golang/govulncheck-action@v1

  golint:
    name: golint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
          skip-cache: true

  gotest:
    name: gotest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: go test
        run: go test ./... -count=1 -coverpkg=./... -coverprofile=./cover.out
      - name: check coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml

