name: Run testing

on:
  push:
    branches:
      - master

jobs:
  go-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: use golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: go get
        run: go get ./...
      - name: go lint
        run: go tool golangci-lint run ./...

  go-test-integration:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: use golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: go get
        run: go get ./...
      - name: go test
        run: go test -v -count=1 -coverpkg=./... -coverprofile=./coverage.out ./tests/...
